"""correção

Revision ID: c7068fd5906b
Revises: b963e856f283
Create Date: 2025-09-08 23:47:35.418812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7068fd5906b'
down_revision: Union[str, Sequence[str], None] = 'b963e856f283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('name', sa.String(length=200), nullable=False))
    op.drop_column('clients', 'named')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('named', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('clients', 'name')
    # ### end Alembic commands ###
